Repository pranjay-poddar/Dev-Geeks, pull requests merged in 2022-10, with the labels that each got.

#469 added documentation
  CODE_OF_CONDUCT.md
  Contributing_Guidelines.md
Labels: hacktoberfest-accepted

#503 Update test.ts
  AngularJS Projects/angular-route/src/test.ts
Labels: hacktoberfest-accepted

#514 Added BMI Calculator in React Projects
  README.md
  React-JS Projects/bmi-calculator/.gitignore
  React-JS Projects/bmi-calculator/package-lock.json
  React-JS Projects/bmi-calculator/package.json
  React-JS Projects/bmi-calculator/public/calculator.png
  React-JS Projects/bmi-calculator/public/index.html
  React-JS Projects/bmi-calculator/public/styles.css
  React-JS Projects/bmi-calculator/src/components/App.jsx
  React-JS Projects/bmi-calculator/src/components/Body.jsx
  React-JS Projects/bmi-calculator/src/components/Footer.jsx
  React-JS Projects/bmi-calculator/src/components/Header.jsx
  React-JS Projects/bmi-calculator/src/components/calculator.gif
  React-JS Projects/bmi-calculator/src/index.js
Labels: hacktoberfest

#706 Analysis and Prediction of the keras fashion dataset using various deep learning models
  ML Projects/Analysis of Fashion_dataset/Fashion dataset.ipynb
  ML Projects/Analysis of Fashion_dataset/README.md
  README.md
Labels: hacktoberfest-accepted

#656 CREATING SPACE WARRIOR GAME FILE
  Python Projects/SPACE WARRIORS/04B_30__.TTF
  Python Projects/SPACE WARRIORS/README.md
  Python Projects/SPACE WARRIORS/__pycache__/loginpage.cpython-38.pyc
  Python Projects/SPACE WARRIORS/__pycache__/main.cpython-38.pyc
  Python Projects/SPACE WARRIORS/assets2/1.png
  Python Projects/SPACE WARRIORS/assets2/11.png
  Python Projects/SPACE WARRIORS/assets2/3.png
  Python Projects/SPACE WARRIORS/assets2/4.png
  Python Projects/SPACE WARRIORS/assets2/7.png
  Python Projects/SPACE WARRIORS/assets2/bg.jpg
  Python Projects/SPACE WARRIORS/assets2/laserBlue16.png
  Python Projects/SPACE WARRIORS/assets2/laserGreen10.png
  Python Projects/SPACE WARRIORS/assets2/laserRed16.png
  Python Projects/SPACE WARRIORS/main.py
  Python Projects/SPACE WARRIORS/requirements.txt
Labels: hacktoberfest

#750 online shopping webaite added
  Frontend-Projects/onlineclothshopping website/images/about-img.png
  Frontend-Projects/onlineclothshopping website/images/accessories/a.png
  Frontend-Projects/onlineclothshopping website/images/accessories/b.png
  Frontend-Projects/onlineclothshopping website/images/accessories/c.png
  Frontend-Projects/onlineclothshopping website/images/accessories/d.png
  Frontend-Projects/onlineclothshopping website/images/accessories/e.png
  Frontend-Projects/onlineclothshopping website/images/accessories/f.png
  Frontend-Projects/onlineclothshopping website/images/banner1.png
  Frontend-Projects/onlineclothshopping website/images/banner2.png
  Frontend-Projects/onlineclothshopping website/images/banner3.png
  Frontend-Projects/onlineclothshopping website/images/footer-img.png
  Frontend-Projects/onlineclothshopping website/images/home-img.png
  Frontend-Projects/onlineclothshopping website/images/men's collect/a.png
  Frontend-Projects/onlineclothshopping website/images/men's collect/b.png
  Frontend-Projects/onlineclothshopping website/images/men's collect/c.png
  Frontend-Projects/onlineclothshopping website/images/men's collect/d.png
  Frontend-Projects/onlineclothshopping website/images/men's collect/e.png
  Frontend-Projects/onlineclothshopping website/images/men's collect/f.png
  Frontend-Projects/onlineclothshopping website/images/men's collect/g.png
  Frontend-Projects/onlineclothshopping website/images/men's collect/h.png
  Frontend-Projects/onlineclothshopping website/images/men's collect/i.png
  Frontend-Projects/onlineclothshopping website/images/offer1.png
  Frontend-Projects/onlineclothshopping website/images/offer2.png
  Frontend-Projects/onlineclothshopping website/images/offer3.png
  Frontend-Projects/onlineclothshopping website/images/testimonial-star.svg
  Frontend-Projects/onlineclothshopping website/images/women's collect/a.png
  Frontend-Projects/onlineclothshopping website/images/women's collect/b.png
  Frontend-Projects/onlineclothshopping website/images/women's collect/c.png
  Frontend-Projects/onlineclothshopping website/images/women's collect/d.png
  Frontend-Projects/onlineclothshopping website/images/women's collect/e.png
  Frontend-Projects/onlineclothshopping website/images/women's collect/f.png
  Frontend-Projects/onlineclothshopping website/images/women's collect/g.png
  Frontend-Projects/onlineclothshopping website/images/women's collect/h.png
  Frontend-Projects/onlineclothshopping website/index.html
  Frontend-Projects/onlineclothshopping website/readme.md
  Frontend-Projects/onlineclothshopping website/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#853 Among Us game
  Js-Games/Among Us Game/assets/audio/Killing_Sound.mp3
  Js-Games/Among Us Game/assets/audio/Sound.mp3
  Js-Games/Among Us Game/assets/images/Amogus_Icon.png
  Js-Games/Among Us Game/assets/images/Crewmate_killed.png
  Js-Games/Among Us Game/assets/images/Crewmate_normal.png
  Js-Games/Among Us Game/assets/images/Impostor_Killing.png
  Js-Games/Among Us Game/assets/images/Impostor_normalWalk.png
  Js-Games/Among Us Game/assets/images/Killing_Animation.png
  Js-Games/Among Us Game/assets/images/Loading_Screen.jpg
  Js-Games/Among Us Game/assets/images/The_Skeld_Cafeteria.png
  Js-Games/Among Us Game/assets/images/kill_button.png
  Js-Games/Among Us Game/index.html
  Js-Games/Among Us Game/script.js
  Js-Games/Among Us Game/style.css
Labels: hacktoberfest-accepted

#796 Virtual Calculator using Python added #788
  Python Projects/VirtualCalculator/.idea/.gitignore
  Python Projects/VirtualCalculator/.idea/VirtualCalculator.iml
  Python Projects/VirtualCalculator/.idea/inspectionProfiles/Project_Default.xml
  Python Projects/VirtualCalculator/.idea/inspectionProfiles/profiles_settings.xml
  Python Projects/VirtualCalculator/.idea/misc.xml
  Python Projects/VirtualCalculator/.idea/modules.xml
  Python Projects/VirtualCalculator/M.py
  Python Projects/VirtualCalculator/main.py
Labels: hacktoberfest-accepted
