Repository pranjay-poddar/Dev-Geeks, pull requests merged in 2023-07, with the labels that each got.

#2853 Added AI-ChatGPT
  AI_ChatGPT/README.md
  AI_ChatGPT/script.js
Labels: level2, gssoc23

#2908 Encrypt Decrypt Using Python Added #2861
  Python Projects/Encrypt-Decrypt/README.md
  Python Projects/Encrypt-Decrypt/main.py
Labels: level2, gssoc23

#3048 #3043 Task_manager added
  Frontend-Projects/Task manager/index.html
  Frontend-Projects/Task manager/script.js
  Frontend-Projects/Task manager/styles.css
Labels: level2, gssoc23

#3057 [GSSoC'23] World Clock Ready
  Js-Projects/World_Clock/README.md
  Js-Projects/World_Clock/index.html
  Js-Projects/World_Clock/script.js
  Js-Projects/World_Clock/style.css
  Js-Projects/World_Clock/timezone.json
Labels: level2, gssoc23

#3272 Frontend Project 'WebPage Project new' Content Alignment Enhancement
  Frontend-Projects/WebPage Project new/style.css
Labels: level1, gssoc23

#3308 Frontend Project 'Travel Website Template' Content Alignment Enhancement
  Frontend-Projects/Travel Website Template/style.css
Labels: level1, gssoc23

#3204 New project
  Animations-CSS/Profile-card/index.html
Labels: level2, gssoc23

#3238 Added Clock Website [GSSOC'23]
  Frontend-Projects/Clock Website/project_clock.html
Labels: level2, gssoc23

#3243 Added Payroll Management [GSSOC'23]
  cpp-projects/Payroll Management/Payroll Management Project.cpp
  cpp-projects/Payroll Management/Records.txt
Labels: level2, gssoc23

#3256 Added Bank Management System [GSSOC'23]
  c_pojects/Bank Management System/bank_management_system.c
  c_pojects/Bank Management System/record.txt
Labels: level2, gssoc23

#3324 Improved the Fall Game [GSSOC'23]
  Js-Games/Fall Game/background_sound.mp3
  Js-Games/Fall Game/index.html
  Js-Games/Fall Game/parallax_background.gif
  Js-Games/Fall Game/script.js
  Js-Games/Fall Game/style.css
Labels: level1, gssoc23

#3404 thought generation Project Styling
  Frontend-Projects/thought generator/style.css
Labels: level1, gssoc23

#3393 Frontend Project "Valient-Institute-Site-main" Contact Form Button Alignment Correction
  Frontend-Projects/Valient-Institute-Site-main/style.css
Labels: level1, gssoc23

#3392 Frontend Project "Valient-Institute-Site-main" Review Section Content Alignment
  Frontend-Projects/Valient-Institute-Site-main/index.html
  Frontend-Projects/Valient-Institute-Site-main/style.css
Labels: level1, gssoc23

#3400 Frontend Project "To Do List" Box Border Shape Improvement
  Frontend-Projects/To Do LIst/styles.css
Labels: level1, gssoc23

#3398 Frontend Project "To-do-list-2" Border Design Enhancement
  Frontend-Projects/To-do-list-2/style.css
Labels: level1, gssoc23

#3397 Frontend Project "Tribute Page" Content Alignment
  Frontend-Projects/Tribute_Page/styles.css
Labels: level1, gssoc23

#3395 Frontend Project "URL Shortener" Paragraph Alignment Enhancement
  Frontend-Projects/URL Shortener/style.css
Labels: level1, gssoc23

#3394 Frontend Project "URL Shortener" Button Alignment Correction
  Frontend-Projects/URL Shortener/style.css
Labels: level1, gssoc23

#3427 added animated contact page
  Animations-CSS/Contact-Us/index.html
Labels: level1, gssoc23

#3431 Added Frontend Project - Temperature Converter
  Footers/Rfooter/index.html
  Footers/content-footer/index.html
  Footers/footer-res/index.html
  Footers/footer-res/style.css
  Footers/footer/index.html
  Footers/footer_new/index.html
  Footers/responsive_footer/index.html
  Frontend-Projects/Temperature Converter Website/img.png
  Frontend-Projects/Temperature Converter Website/index.html
  Frontend-Projects/Temperature Converter Website/main.js
  Frontend-Projects/Temperature Converter Website/style.css
Labels: level2, gssoc23

#3364 Doraemon animation
  Java Projects/Doraemon_Animation/DoraemonAnimation.java
  Java Projects/Doraemon_Animation/Readme.md
Labels: level2, gssoc23

#3425 Added the projects to correct folder
  c_projects/Bank Management System/bank_management_system.c
  c_projects/Bank Management System/record.txt
  c_projects/ZeroesinNumber/ReadMe.md
  c_projects/ZeroesinNumber/Zeroes.c
Labels: level1, gssoc23

#3445 Frontend Project "The coffee house" Menu Section's Buttons Design Improvement
  Frontend-Projects/The coffee house/coffeehouse.css
Labels: level1, gssoc23

#3513 Frontend Project "Task manager" 'Add task' Button Design
  Frontend-Projects/Task manager/styles.css
Labels: level1, gssoc23

#3512 Frontend Project "Task manager" Content Styling
  Frontend-Projects/Task manager/styles.css
Labels: level1, gssoc23

#3518 Frontend Project "Starbucks Frontend" Homepage Paragraph Improved Styling
  Frontend-Projects/Starbucks Frontend/style.css
Labels: level1, gssoc23

#3517 Frontend Project "Sudoku Solver" Buttons Hover Effect Addition
  Frontend-Projects/Sudoku Solver/sudokuSolver/style.css
Labels: level1, gssoc23

#3523 Resume-maker added
  Frontend-Projects/resume-maker/index.html
  Frontend-Projects/resume-maker/index.js
  Frontend-Projects/resume-maker/styles.css
Labels: level1, gssoc23

#3515 Frontend Project "Sudoku Solver" Buttons Styling
  Frontend-Projects/Sudoku Solver/sudokuSolver/style.css
Labels: level1, gssoc23

#3444 Frontend Project "The coffee house" Footer Design
  Frontend-Projects/The coffee house/coffeehouse.css
Labels: level1, gssoc23

#3602 hover effect to social media icons
  Frontend-Projects/AdventureAwaits/css/styles.css
  Frontend-Projects/AdventureAwaits/index.html
Labels: level1, gssoc23

#3576 decimal to binary converter
  c_projects/Decimal to Binary/ReadMe.md
  c_projects/Decimal to Binary/decimal_to_binary.c
Labels: level2, gssoc23

#3468 tambolagame
  Python Projects/tambola game/README.md
  Python Projects/tambola game/images/img1.jpeg
  Python Projects/tambola game/images/img2.jpeg
  Python Projects/tambola game/images/img3.jpeg
  Python Projects/tambola game/tambola_.py
Labels: level2, gssoc23

#3592 Frontend Project "Sky Scapper game" Button 'Start' Improved Styling
  Frontend-Projects/Sky Scapper game/style.css
Labels: level1, gssoc23

#3593 Frontend Project "SIGN UP FORM" Improved Styling
  Frontend-Projects/SIGN UP FORM/style.css
Labels: level1, gssoc23

#3596 Frontend Project "Sample-Frontend-Project" 'What is CRAZYSTOCKS' Section Styling
  Frontend-Projects/Sample-Frontend-Project/style.css
Labels: level1, gssoc23

#3597 Frontend Project "Sample-Frontend-Project" Login Form Styling
  Frontend-Projects/Sample-Frontend-Project/style.css
Labels: level1, gssoc23

#3598 Frontend Project "Sample-Frontend-Project" 'Check Out Our Specialized Services' Section Styling
  Frontend-Projects/Sample-Frontend-Project/style.css
Labels: level1, gssoc23

#3600 Frontend Project "Sample-Frontend-Project" 'Contact Us Now' Section Styling
  Frontend-Projects/Sample-Frontend-Project/style.css
Labels: level1, gssoc23

#3599 Frontend Project "Sample-Frontend-Project" 'Here’s what our users have to say' Section Styling
  Frontend-Projects/Sample-Frontend-Project/style.css
Labels: level1, gssoc23

#3605 Frontend Project "Random Color Generator" Improved Design
  Frontend-Projects/Random Color Generator/style.css
Labels: level1, gssoc23

#3607 Frontend Project "Random-image-slider" Improved Styling
  Frontend-Projects/Random-image-slider/index.html
  Frontend-Projects/Random-image-slider/styles.css
Labels: level1, gssoc23

#3610 Frontend Project "Recipe_Book" Styling
  Frontend-Projects/Recipe_Book/style.css
Labels: level1, gssoc23

#3613 Frontend Project "razorpayClone" 'Explore Razorpay Business Banking' Section Uneven Color Correction
  Frontend-Projects/razorpayClone/index.html
Labels: level1, gssoc23

#3612 Frontend Project "registration form" Updated Design
  Frontend-Projects/registration form/index.html
  Frontend-Projects/registration form/styles.css
Labels: level1, gssoc23

#3614 Frontend Project "Realtime Character Counter" Styling
  Frontend-Projects/Realtime Character Counter/style.css
Labels: level1, gssoc23

#3590 Frontend Project "smart wearbles website" Content Styling
  Frontend-Projects/smart wearbles website/index.html
Labels: level1, gssoc23

#3594 Frontend Project "Sample-Frontend-Project" Navbar Improved Styling
  Frontend-Projects/Sample-Frontend-Project/style.css
Labels: level1, gssoc23

#3695 Frontend Project "Pixel Art Generator" Styling
  Frontend-Projects/Pixel Art Generator/index.html
  Frontend-Projects/Pixel Art Generator/style.css
Labels: level1, gssoc23

#3698 Frontend Project "PrimeFlix" 'Even better with Fire TV Stick' Section Improved Alignment
  Frontend-Projects/PrimeFlix/Welcome to Prime Video.html
  Frontend-Projects/PrimeFlix/Welcome to Prime Video_files/styles.css
Labels: level1, gssoc23

#3697 Frontend Project "Portfolio" Navbar Color Correction
  Frontend-Projects/Portfolio/style.css
Labels: level1, gssoc23

#3773 Create phone.cpp
  cpp-projects/Phone directory/phone.cpp
Labels: level1, gssoc23

#3228 Adding speech-to-text project
  React-JS Projects/speech-to-text/.gitignore
  React-JS Projects/speech-to-text/README.md
  React-JS Projects/speech-to-text/package-lock.json
  React-JS Projects/speech-to-text/package.json
  React-JS Projects/speech-to-text/public/favicon.ico
  React-JS Projects/speech-to-text/public/index.html
  React-JS Projects/speech-to-text/public/logo192.png
  React-JS Projects/speech-to-text/public/logo512.png
  React-JS Projects/speech-to-text/public/manifest.json
  React-JS Projects/speech-to-text/public/robots.txt
  React-JS Projects/speech-to-text/src/App.css
  React-JS Projects/speech-to-text/src/App.js
  React-JS Projects/speech-to-text/src/index.css
  React-JS Projects/speech-to-text/src/index.js
  React-JS Projects/speech-to-text/src/reportWebVitals.js
  React-JS Projects/speech-to-text/src/setupTests.js
Labels: level2, gssoc23

#3287 Adding whack-a-mole game
  Js-Games/Whack-a-mole/background.jpg
  Js-Games/Whack-a-mole/index.html
  Js-Games/Whack-a-mole/mole-image.jpg
  Js-Games/Whack-a-mole/pngtree-mole-image.jpg
  Js-Games/Whack-a-mole/script.js
  Js-Games/Whack-a-mole/style.css
  Js-Games/Whack-a-mole/whack-a-mole.png
Labels: level2, gssoc23

#3298 Temperature converter
  Frontend-Projects/temperature converter/about.txt
  Frontend-Projects/temperature converter/android-chrome-192x192.png
  Frontend-Projects/temperature converter/android-chrome-512x512.png
  Frontend-Projects/temperature converter/apple-touch-icon.png
  Frontend-Projects/temperature converter/bg.jpg
  Frontend-Projects/temperature converter/favicon-16x16.png
  Frontend-Projects/temperature converter/favicon-32x32.png
  Frontend-Projects/temperature converter/favicon.ico
  Frontend-Projects/temperature converter/favicon_io.zip
  Frontend-Projects/temperature converter/index.html
  Frontend-Projects/temperature converter/readme.md
  Frontend-Projects/temperature converter/script.js
  Frontend-Projects/temperature converter/site.webmanifest
  Frontend-Projects/temperature converter/style.css
Labels: level2, gssoc23

#3508 Added a new game DoodleJump
  Js-Games/DoodleJump/README.md
  Js-Games/DoodleJump/favicon.ico
  Js-Games/DoodleJump/image.png
  Js-Games/DoodleJump/index.html
  Js-Games/DoodleJump/script.js
  Js-Games/DoodleJump/style.css
Labels: level2, gssoc23

#3459 Edge detector added
  ML Projects/Edge Detection/algorithm - dataset.md
  ML Projects/Edge Detection/algorithm_dataset.ipynb
Labels: level2, gssoc23

#3458 Anime Recommender added
  ML Projects/Anime Predictor/Anime Predictor.ipynb
  ML Projects/Anime Predictor/readme.md
Labels: level2, gssoc23

#3430 Image classification project added - GSSOC'23
  Python Projects/Image Classification/README.md
  Python Projects/Image Classification/image_classification.py
  README.md
Labels: level2, gssoc23

#3428 Youtube-bookmarker extension project added in the Js-Projects folder
  Js-Projects/YT-Bookmarker-extension/README.md
  Js-Projects/YT-Bookmarker-extension/assets/bookmark.png
  Js-Projects/YT-Bookmarker-extension/assets/delete.png
  Js-Projects/YT-Bookmarker-extension/assets/edit.png
  Js-Projects/YT-Bookmarker-extension/assets/ext-icon.png
  Js-Projects/YT-Bookmarker-extension/assets/play.png
  Js-Projects/YT-Bookmarker-extension/assets/save.png
  Js-Projects/YT-Bookmarker-extension/background.js
  Js-Projects/YT-Bookmarker-extension/contentScript.js
  Js-Projects/YT-Bookmarker-extension/manifest.json
  Js-Projects/YT-Bookmarker-extension/popup.css
  Js-Projects/YT-Bookmarker-extension/popup.html
  Js-Projects/YT-Bookmarker-extension/popup.js
  Js-Projects/YT-Bookmarker-extension/utils.js
Labels: level3, gssoc23

#3423 Added hover effect under link in footer section
  Devgeeks website/style.css
Labels: level1, gssoc23

#3646 Added Movers and Packers Website
  Frontend-Projects/Movers and Packers Website/README.md
  Frontend-Projects/Movers and Packers Website/index.html
Labels: level2, gssoc23

#3305 navbar with a sidebar added
  Navbars/Sidebar/index.html
  Navbars/Sidebar/index.js
  Navbars/Sidebar/style.css
Labels: level2, gssoc23

#3302 House price prediction
  ML Projects/House Price prediction using Regression model/House_Price_Prediction.ipynb
  ML Projects/House Price prediction using Regression model/readme.md
Labels: level2, gssoc23

#3295 GeeksforGeeks Clone Project
  Frontend-Projects/GeeksforGeeks Clone/box-13.png
  Frontend-Projects/GeeksforGeeks Clone/box-14.png
  Frontend-Projects/GeeksforGeeks Clone/box1.0.png
  Frontend-Projects/GeeksforGeeks Clone/box1.png
  Frontend-Projects/GeeksforGeeks Clone/box2.png
  Frontend-Projects/GeeksforGeeks Clone/box3.png
  Frontend-Projects/GeeksforGeeks Clone/box4.png
  Frontend-Projects/GeeksforGeeks Clone/box5.png
  Frontend-Projects/GeeksforGeeks Clone/box6.png
  Frontend-Projects/GeeksforGeeks Clone/box7.png
  Frontend-Projects/GeeksforGeeks Clone/gfg logo.png
  Frontend-Projects/GeeksforGeeks Clone/index.html
  Frontend-Projects/GeeksforGeeks Clone/style.css
Labels: level2, gssoc23

#3257 Bullseye Game
  Js-Games/Bullseye Game/dist/index.html
  Js-Games/Bullseye Game/dist/script.js
  Js-Games/Bullseye Game/dist/style.css
Labels: level2, gssoc23

#3222 Google_Drive_Clone
  Frontend-Projects/Google_Drive_clone/index.html
  Frontend-Projects/Google_Drive_clone/profile.pic.jpg
  Frontend-Projects/Google_Drive_clone/style.css
Labels: level2, gssoc23

#3217 favicon added new pr
  Devgeeks website/index.html
Labels: level1, gssoc23

#3215 Added food truck project to frontend
  Frontend-Projects/Food Truck/package-lock.json
  Frontend-Projects/Food Truck/package.json
  Frontend-Projects/Food Truck/public/images/Vector 1.png
  Frontend-Projects/Food Truck/public/images/fb.png
  Frontend-Projects/Food Truck/public/images/food-truck.png
  Frontend-Projects/Food Truck/public/images/insta.png
  Frontend-Projects/Food Truck/public/images/meal-prep-ideas-1.png
  Frontend-Projects/Food Truck/public/images/meal-prep-ideas-2.png
  Frontend-Projects/Food Truck/public/images/meal-prep-ideas-3.png
  Frontend-Projects/Food Truck/public/images/meal-prep-ideas-4.png
  Frontend-Projects/Food Truck/public/images/meal-prep-ideas-5.png
  Frontend-Projects/Food Truck/public/images/meal-prep-ideas-6.png
  Frontend-Projects/Food Truck/public/images/pharmasict-serving-customer-drug-store.png
  Frontend-Projects/Food Truck/public/images/pizza.png
  Frontend-Projects/Food Truck/public/images/twitter.png
  Frontend-Projects/Food Truck/public/index.html
  Frontend-Projects/Food Truck/public/styles.css
  Frontend-Projects/Food Truck/src/components/About.jsx
  Frontend-Projects/Food Truck/src/components/App.js
  Frontend-Projects/Food Truck/src/components/Article.jsx
  Frontend-Projects/Food Truck/src/components/Banner.jsx
  Frontend-Projects/Food Truck/src/components/Footer.jsx
  Frontend-Projects/Food Truck/src/components/Item.jsx
  Frontend-Projects/Food Truck/src/index.js
Labels: level2, gssoc23

#3185 Added music player
  Python Projects/Music Player/English Songs/WhatsApp Audio 2022-12-15 at 13.25.21 (1).mpeg
  Python Projects/Music Player/English Songs/WhatsApp Audio 2022-12-15 at 13.25.21.mpeg
  Python Projects/Music Player/English Songs/WhatsApp Audio 2022-12-15 at 13.25.22 (1).mpeg
  Python Projects/Music Player/English Songs/WhatsApp Audio 2022-12-15 at 13.25.22.mpeg
  Python Projects/Music Player/Hindi Songs/WhatsApp Audio 2022-12-15 at 13.25.04 (1).mpeg
  Python Projects/Music Player/Hindi Songs/WhatsApp Audio 2022-12-15 at 13.25.04.mpeg
  Python Projects/Music Player/Hindi Songs/WhatsApp Audio 2022-12-15 at 13.25.05 (1).mpeg
  Python Projects/Music Player/Hindi Songs/WhatsApp Audio 2022-12-15 at 13.25.05.mpeg
  Python Projects/Music Player/Sample.py
  Python Projects/Music Player/images.jpeg
  Python Projects/Music Player/music.gif
  Python Projects/Music Player/next.gif
  Python Projects/Music Player/pause.gif
  Python Projects/Music Player/play.gif
  Python Projects/Music Player/previous.gif
  Python Projects/Music Player/songs.pickle
Labels: level2, gssoc23

#3183 Added Simple Maze
  Js-Games/Maze/ReadMe.md
  Js-Games/Maze/index.html
  Js-Games/Maze/main.js
Labels: level2, gssoc23

#3807 added transition & animation to buttons
  Frontend-Projects/Animated Portfolio/index.html
  Frontend-Projects/Animated Portfolio/style.css
Labels: level2, gssoc23

#3797 Added Connecting Particles JS Interactive Animation
  Animations-JS/Connecting Particles/README.md
  Animations-JS/Connecting Particles/index.html
  Animations-JS/Connecting Particles/script.js
  Animations-JS/Connecting Particles/styles.css
Labels: level2, gssoc23

#3796 Added Colorful Interactive Particles using Javascript
  Animations-JS/Colorful Interactive Particles/README.md
  Animations-JS/Colorful Interactive Particles/index.html
  Animations-JS/Colorful Interactive Particles/script.js
  Animations-JS/Colorful Interactive Particles/styles.css
Labels: level2, gssoc23

#3780 News App project Added
  Js-Projects/News App/index.html
  Js-Projects/News App/logo.jpg
  Js-Projects/News App/script.js
  Js-Projects/News App/style.css
Labels: level2, gssoc23

#3759 Added AI image generator project
  Python Projects/AI Image Generator/README.md
  Python Projects/AI Image Generator/imggen.py
  README.md
Labels: level2, gssoc23

#3822 React Admin Dashboard App [GSSoC'23] #1651
  React-JS Projects/Admin + (Admin Dashboard)/.gitignore
  React-JS Projects/Admin + (Admin Dashboard)/README.md
  React-JS Projects/Admin + (Admin Dashboard)/package-lock.json
  React-JS Projects/Admin + (Admin Dashboard)/package.json
  React-JS Projects/Admin + (Admin Dashboard)/postcss.config.js
  React-JS Projects/Admin + (Admin Dashboard)/public/index.html
  React-JS Projects/Admin + (Admin Dashboard)/public/logo.png
  React-JS Projects/Admin + (Admin Dashboard)/src/App.js
  React-JS Projects/Admin + (Admin Dashboard)/src/assets/avatar.png
  React-JS Projects/Admin + (Admin Dashboard)/src/assets/logo.png
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Analytics/Chart.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Auth/LoginForm.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Auth/PasswordReset.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Auth/Registration.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Calendar Integration/Calendar.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Calendar Integration/EventForm.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Dashboard/Dashboard.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/DataManagement/Data.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/DataManagement/DataChart.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Error Handling/NotFound.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Inbox/Inbox.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Layout/Footer.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Layout/HomePage.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Navigation/Sidebar.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Notifications/NotificationList.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Settings/Settings.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/Tasks/TaskForm.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/User Management/UserActivity.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/User Management/UserDetail.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/User Management/UserForm.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/User Management/UserList.js
  React-JS Projects/Admin + (Admin Dashboard)/src/components/User Management/Users.js
  React-JS Projects/Admin + (Admin Dashboard)/src/index.css
  React-JS Projects/Admin + (Admin Dashboard)/src/index.js
  React-JS Projects/Admin + (Admin Dashboard)/tailwind.config.js
Labels: level2, gssoc23

#3845 [NEW PROJECT] Chess Website
  Frontend-Projects/Chess Website/README.md
  Frontend-Projects/Chess Website/index.html
  Frontend-Projects/Chess Website/script.js
  Frontend-Projects/Chess Website/style.css
Labels: level2, gssoc23

#3608 Added Video Conferencing Web Application
  MERN/VedioConferencing/README.md
  MERN/VedioConferencing/package-lock.json
  MERN/VedioConferencing/package.json
  MERN/VedioConferencing/public/chat.html
  MERN/VedioConferencing/public/css/style.css
  MERN/VedioConferencing/public/index.html
  MERN/VedioConferencing/public/js/main.js
  MERN/VedioConferencing/server.js
  MERN/VedioConferencing/utils/messages.js
  MERN/VedioConferencing/utils/users.js
Labels: level2, gssoc23

#3382 Added a new stickman game
  Js-Games/StickmanGame/Sounds/Sword_sound.wav
  Js-Games/StickmanGame/Sounds/jump_sound.wav
  Js-Games/StickmanGame/Stickman Game.html
  Js-Games/StickmanGame/block.js
  Js-Games/StickmanGame/collision.js
  Js-Games/StickmanGame/enemyMovement.js
  Js-Games/StickmanGame/entity.js
  Js-Games/StickmanGame/for vs eval.html
  Js-Games/StickmanGame/graphics.js
  Js-Games/StickmanGame/map creator.html
  Js-Games/StickmanGame/movement.js
  Js-Games/StickmanGame/string performance test.html
  Js-Games/StickmanGame/util.js
Labels: level2, gssoc23

#3905 Slot machine game
  Python Projects/Slot-Machine-Game/README.md
  Python Projects/Slot-Machine-Game/slotmachine.py
Labels: level2, gssoc23

#3923 Kaleidoscope Animation[GSSOC'23]
  Animations-CSS/Kaleidoscope Animation/README.md
  Animations-CSS/Kaleidoscope Animation/index.html
  Animations-CSS/Kaleidoscope Animation/style.css
Labels: level2, gssoc23

#3922 Submarine Animation[GSSOC'23]
  Animations-CSS/Submarine Animation/README.md
  Animations-CSS/Submarine Animation/index.html
  Animations-CSS/Submarine Animation/style.css
Labels: level2, gssoc23

#3921 Thought-generator added
  Frontend-Projects/Thought-generator/index.html
  Frontend-Projects/Thought-generator/index.js
  Frontend-Projects/Thought-generator/styles.css
Labels: level2, gssoc23

#3920 Country-search-app added
  Frontend-Projects/Country-search App/index.html
  Frontend-Projects/Country-search App/index.js
  Frontend-Projects/Country-search App/styles.css
Labels: level2, gssoc23

#3919 Pokemon-information generator added
  Frontend-Projects/pokemon-information generator/index.html
  Frontend-Projects/pokemon-information generator/index.js
  Frontend-Projects/pokemon-information generator/styles.css
Labels: level2, gssoc23

#3954 added a Todo List
  React-JS Projects/ToDo List/.gitignore
  React-JS Projects/ToDo List/README.md
  React-JS Projects/ToDo List/package-lock.json
  React-JS Projects/ToDo List/package.json
  React-JS Projects/ToDo List/public/favicon.ico
  React-JS Projects/ToDo List/public/index.html
  React-JS Projects/ToDo List/public/logo192.png
  React-JS Projects/ToDo List/public/logo512.png
  React-JS Projects/ToDo List/public/manifest.json
  React-JS Projects/ToDo List/public/robots.txt
  React-JS Projects/ToDo List/src/App.css
  React-JS Projects/ToDo List/src/App.js
  React-JS Projects/ToDo List/src/components/login.css
  React-JS Projects/ToDo List/src/components/login.js
  React-JS Projects/ToDo List/src/components/todo_page.css
  React-JS Projects/ToDo List/src/components/todo_page.js
  React-JS Projects/ToDo List/src/firebase.js
  React-JS Projects/ToDo List/src/index.js
  React-JS Projects/ToDo List/src/styles.css
Labels: level2, gssoc23

#3950 Added a Book Scraper
  Python Projects/Book Scraper/README.md
  Python Projects/Book Scraper/main.py
  Python Projects/Book Scraper/requirements.txt
Labels: level2, gssoc23

#3949 Added the Spotify Clone [GSSOC'23]
  React-JS Projects/Spotify Clone/.gitignore
  React-JS Projects/Spotify Clone/README.md
  React-JS Projects/Spotify Clone/package-lock.json
  React-JS Projects/Spotify Clone/package.json
  React-JS Projects/Spotify Clone/public/index.html
  React-JS Projects/Spotify Clone/public/manifest.json
  React-JS Projects/Spotify Clone/public/robots.txt
  React-JS Projects/Spotify Clone/src/App.css
  React-JS Projects/Spotify Clone/src/App.js
  React-JS Projects/Spotify Clone/src/Body.css
  React-JS Projects/Spotify Clone/src/Body.js
  React-JS Projects/Spotify Clone/src/Footer.css
  React-JS Projects/Spotify Clone/src/Footer.js
  React-JS Projects/Spotify Clone/src/Header.css
  React-JS Projects/Spotify Clone/src/Header.js
  React-JS Projects/Spotify Clone/src/Login.css
  React-JS Projects/Spotify Clone/src/Login.js
  React-JS Projects/Spotify Clone/src/Player.css
  React-JS Projects/Spotify Clone/src/Player.js
  React-JS Projects/Spotify Clone/src/Sidebar.css
  React-JS Projects/Spotify Clone/src/Sidebar.js
  React-JS Projects/Spotify Clone/src/SidebarOption.css
  React-JS Projects/Spotify Clone/src/SidebarOption.js
  React-JS Projects/Spotify Clone/src/SongRow.css
  React-JS Projects/Spotify Clone/src/SongRow.js
  React-JS Projects/Spotify Clone/src/StateProvider.js
  React-JS Projects/Spotify Clone/src/index.css
  React-JS Projects/Spotify Clone/src/index.js
  React-JS Projects/Spotify Clone/src/reducer.js
  React-JS Projects/Spotify Clone/src/reportWebVitals.js
  React-JS Projects/Spotify Clone/src/serviceWorker.js
  React-JS Projects/Spotify Clone/src/spotify.js
Labels: level3, gssoc23

#3941 revamp: dev-geeks footer style ✨
  Repository_web_page/index.html
  Repository_web_page/new/style.css
Labels: level1, gssoc23

#3988 'Women's Collection' Section Styling
  Frontend-Projects/onlineclothshopping website/index.html
  Frontend-Projects/onlineclothshopping website/style.css
Labels: level1, gssoc23

#3991 Added a Order Complete Button
  Animations-CSS/Order-Complete-Button/index.html
  Animations-CSS/Order-Complete-Button/script.js
  Animations-CSS/Order-Complete-Button/style.css
Labels: level1, gssoc23

#4069 [Add a new project] Bus booking management System using python [gssoc23]
  Python Projects/Bus booking management System/README.md
  Python Projects/Bus booking management System/main.py
Labels: level2, gssoc23

#4059 Komal gssoc23 ebike project
  Frontend-Projects/Ebike website/homepage/homenew.html
  Frontend-Projects/Ebike website/homepage/homepagenew.css
Labels: level2, gssoc23

#4037 Speech through text added
  Frontend-Projects/speech-to-text/index.html
  Frontend-Projects/speech-to-text/index.js
  Frontend-Projects/speech-to-text/styles.css
Labels: level2, gssoc23

#4014 quiz game
  c_projects/Quiz game/ReadMe.md
  c_projects/Quiz game/quizGame.c
Labels: level2, gssoc23

#4003 Wordle Project Added in the React-JS Projects folder
  React-JS Projects/Wordle/wordle/.gitignore
  React-JS Projects/Wordle/wordle/README.md
  React-JS Projects/Wordle/wordle/package-lock.json
  React-JS Projects/Wordle/wordle/package.json
  React-JS Projects/Wordle/wordle/public/favicon.ico
  React-JS Projects/Wordle/wordle/public/index.html
  React-JS Projects/Wordle/wordle/public/logo192.png
  React-JS Projects/Wordle/wordle/public/logo512.png
  React-JS Projects/Wordle/wordle/public/manifest.json
  React-JS Projects/Wordle/wordle/public/robots.txt
  React-JS Projects/Wordle/wordle/src/App.css
  React-JS Projects/Wordle/wordle/src/App.js
  React-JS Projects/Wordle/wordle/src/Words.js
  React-JS Projects/Wordle/wordle/src/components/Board.js
  React-JS Projects/Wordle/wordle/src/components/GameOver.js
  React-JS Projects/Wordle/wordle/src/components/Key.js
  React-JS Projects/Wordle/wordle/src/components/Keyboard.js
  React-JS Projects/Wordle/wordle/src/components/Letter.js
  React-JS Projects/Wordle/wordle/src/index.js
  React-JS Projects/Wordle/wordle/src/reportWebVitals.js
  React-JS Projects/Wordle/wordle/src/wordle-bank.txt
Labels: level2, gssoc23

#4271 Credit Risk Assessment in JAVA
  Java Projects/Credit Risk Assessment/README.md
  Java Projects/Credit Risk Assessment/credit.java
Labels: level2, gssoc23

#4337 Added Covid-Info project
  Python Projects/Covid Info/README.md
  Python Projects/Covid Info/covidinfo.py
  README.md
Labels: level2, gssoc23

#4341 Lazy Loading Animation added
  Js-Projects/Lazy Loading/README.md
  Js-Projects/Lazy Loading/app.js
  Js-Projects/Lazy Loading/index.html
  Js-Projects/Lazy Loading/style.css
  README.md
Labels: level2, gssoc23

#4369 Added ATM Machine CLI Project in Java
  Java Projects/ATM Machine/ATM/Account.java
  Java Projects/ATM Machine/ATM/OptionMenu.java
  Java Projects/ATM Machine/ATM/atm.java
  Java Projects/ATM Machine/README.md
  README.md
Labels: level2, gssoc23

#4342 #3787 New project added
  Frontend-Projects/Astromania/Thank-styles.css
  Frontend-Projects/Astromania/Thank-you.html
  Frontend-Projects/Astromania/index.html
  Frontend-Projects/Astromania/styles.css
Labels: level2, gssoc23

#4396 #4289 Musical floor animation
  Frontend-Projects/musical floor/assets/casio--9759.mp3
  Frontend-Projects/musical floor/assets/casio-9757.mp3
  Frontend-Projects/musical floor/assets/data-6460.mp3
  Frontend-Projects/musical floor/assets/do-80236.mp3
  Frontend-Projects/musical floor/assets/fa-78409.mp3
  Frontend-Projects/musical floor/assets/g-6200.mp3
  Frontend-Projects/musical floor/assets/la-80237.mp3
  Frontend-Projects/musical floor/assets/mi-80239.mp3
  Frontend-Projects/musical floor/assets/piano-37898.mp3
  Frontend-Projects/musical floor/assets/re-78500.mp3
  Frontend-Projects/musical floor/assets/si-80238.mp3
  Frontend-Projects/musical floor/assets/sol-101774.mp3
  Frontend-Projects/musical floor/assets/typing-sound-effect-117679.mp3
  Frontend-Projects/musical floor/index.html
  Frontend-Projects/musical floor/scripts.js
  Frontend-Projects/musical floor/styles.css
Labels: level2, gssoc23
