Repository pranjay-poddar/Dev-Geeks, pull requests merged in 2023-06, with the labels that each got.

#1786 Add Plankman game
  Frontend-Projects/Plankman/README.md
  Frontend-Projects/Plankman/index.html
  Frontend-Projects/Plankman/style.css
  README.md
Labels: level2, gssoc23

#1544 Background Color Change
  Js-Projects/Background_Color_Change/index.html
  Js-Projects/Background_Color_Change/readme.md
  Js-Projects/Background_Color_Change/script.js
  Js-Projects/Background_Color_Change/style.css
Labels: level2, gssoc23

#1883 Solved issue: #1733
  Repository_web_page/index.html
Labels: level1, gssoc23

#1867 Fixed Grammatical mistake
  Frontend-Projects/Communicore/index.html
  Frontend-Projects/Educational Course website/index.html
  Frontend-Projects/Netflix Clone/index.html
  Frontend-Projects/Responsive Travel Website/index.html
Labels: level1, gssoc23

#1735 [GSSoC'23] Add Sokoban Game
  Js-Games/sokoban/index.html
  Js-Games/sokoban/style.css
Labels: level2, gssoc23

#1910 navbar with night mode
  Frontend-Projects/BeautifulTweets/Readme.md
  Frontend-Projects/BeautifulTweets/index.html
  Frontend-Projects/BeautifulTweets/style.css
Labels: level2, gssoc23

#1876 Added dark mode theme and change some style and added more products
  React-JS Projects/responsive-product-component/package-lock.json
  React-JS Projects/responsive-product-component/package.json
  React-JS Projects/responsive-product-component/src/App.css
  React-JS Projects/responsive-product-component/src/App.jsx
  React-JS Projects/responsive-product-component/src/component/product-view/Darkmode.jsx
  React-JS Projects/responsive-product-component/src/component/product-view/models/sampleSchema.js
  React-JS Projects/responsive-product-component/src/component/product-view/product-view.component.jsx
  React-JS Projects/responsive-product-component/src/component/product-view/product-view.css
  React-JS Projects/responsive-product-component/src/main.jsx
Labels: level2, gssoc23

#1878 Flights and hotel rooms booking website
  Frontend-Projects/agoda clone/images/agoda-logo-v2.png
  Frontend-Projects/agoda clone/images/bg-agoda-homepage.png
  Frontend-Projects/agoda clone/images/bg-sprite-partner_v3@2x.png
  Frontend-Projects/agoda clone/images/entire-apartment.jpg
  Frontend-Projects/agoda clone/images/entire-bungalow.jpg
  Frontend-Projects/agoda clone/images/entire-house.jpg
  Frontend-Projects/agoda clone/images/entire-villa.jpg
  Frontend-Projects/agoda clone/images/flag-us@2x.png
  Frontend-Projects/agoda clone/index.html
  Frontend-Projects/agoda clone/readme.md
  Frontend-Projects/agoda clone/styles.css
Labels: level2, gssoc23

#1918 Added Blog Website
  Node-JS Projects/Blog_website/.gitignore
  Node-JS Projects/Blog_website/README.md
  Node-JS Projects/Blog_website/app.js
  Node-JS Projects/Blog_website/package-lock.json
  Node-JS Projects/Blog_website/package.json
  Node-JS Projects/Blog_website/public/.DS_Store
  Node-JS Projects/Blog_website/public/css/styles.css
  Node-JS Projects/Blog_website/views/.DS_Store
  Node-JS Projects/Blog_website/views/about.ejs
  Node-JS Projects/Blog_website/views/compose.ejs
  Node-JS Projects/Blog_website/views/contact.ejs
  Node-JS Projects/Blog_website/views/home.ejs
  Node-JS Projects/Blog_website/views/partials/footer.ejs
  Node-JS Projects/Blog_website/views/partials/header.ejs
  Node-JS Projects/Blog_website/views/post.ejs
  README.md
Labels: level1, gssoc23

#1869 Fixed Home URL
  Frontend-Projects/Responsive Travel Website/index.html
Labels: level1, gssoc23

#1926 PASSWORD GENERATOR #1915
  PASSWORD GENERATOR #1915/Readme
  PASSWORD GENERATOR #1915/index.html
Labels: level1, gssoc23

#1936 Added footer in Apple Ecomerce
  Frontend-Projects/Apple Ecommerce/index.html
  Frontend-Projects/Apple Ecommerce/style.css
Labels: level1, gssoc23

#1813 Mayurikothari299 patch 1
  Js-Projects/Grade calculator/index.html
  Js-Projects/Grade calculator/readme
  Js-Projects/Grade calculator/script.js
  Js-Projects/Grade calculator/style.css
Labels: level1, gssoc23

#1415 Elixir based Project
  Elixir Projects/Counter_project/.dockerignore
  Elixir Projects/Counter_project/.formatter.exs
  Elixir Projects/Counter_project/.gitattributes
  Elixir Projects/Counter_project/.gitignore
  Elixir Projects/Counter_project/Dockerfile
  Elixir Projects/Counter_project/README.md
  Elixir Projects/Counter_project/assets/css/app.css
  Elixir Projects/Counter_project/assets/css/phoenix.css
  Elixir Projects/Counter_project/assets/js/app.js
  Elixir Projects/Counter_project/assets/tailwind.config.js
  Elixir Projects/Counter_project/assets/vendor/topbar.js
  Elixir Projects/Counter_project/config/config.exs
  Elixir Projects/Counter_project/config/dev.exs
  Elixir Projects/Counter_project/config/prod.exs
  Elixir Projects/Counter_project/config/runtime.exs
  Elixir Projects/Counter_project/config/test.exs
  Elixir Projects/Counter_project/counter.exs
  Elixir Projects/Counter_project/elixir_buildpack.config
  Elixir Projects/Counter_project/erl_crash.dump
  Elixir Projects/Counter_project/fly.toml
  Elixir Projects/Counter_project/lib/counter.ex
  Elixir Projects/Counter_project/lib/counter/application.ex
  Elixir Projects/Counter_project/lib/counter_web.ex
  Elixir Projects/Counter_project/lib/counter_web/controllers/page_controller.ex
  Elixir Projects/Counter_project/lib/counter_web/endpoint.ex
  Elixir Projects/Counter_project/lib/counter_web/live/page_live.ex
  Elixir Projects/Counter_project/lib/counter_web/live/page_live.html.heex
  Elixir Projects/Counter_project/lib/counter_web/router.ex
  Elixir Projects/Counter_project/lib/counter_web/telemetry.ex
  Elixir Projects/Counter_project/lib/counter_web/templates/layout/app.html.heex
  Elixir Projects/Counter_project/lib/counter_web/templates/layout/live.html.heex
  Elixir Projects/Counter_project/lib/counter_web/templates/layout/root.html.heex
  Elixir Projects/Counter_project/lib/counter_web/templates/page/index.html.heex
  Elixir Projects/Counter_project/lib/counter_web/views/error_helpers.ex
  Elixir Projects/Counter_project/lib/counter_web/views/error_view.ex
  Elixir Projects/Counter_project/lib/counter_web/views/layout_view.ex
  Elixir Projects/Counter_project/lib/counter_web/views/page_view.ex
  Elixir Projects/Counter_project/mix.exs
  Elixir Projects/Counter_project/mix.lock
  Elixir Projects/Counter_project/phoenix_static_buildpack.config
  Elixir Projects/Counter_project/priv/static/favicon.ico
  Elixir Projects/Counter_project/priv/static/images/phoenix.png
  Elixir Projects/Counter_project/priv/static/robots.txt
  Elixir Projects/Counter_project/rel/overlays/bin/server
  Elixir Projects/Counter_project/rel/overlays/bin/server.bat
  Elixir Projects/Counter_project/sample.sh
  Elixir Projects/Counter_project/test/counter_web/controllers/page_controller_test.exs
  Elixir Projects/Counter_project/test/counter_web/live/page_live_test.exs
  Elixir Projects/Counter_project/test/counter_web/views/error_view_test.exs
  Elixir Projects/Counter_project/test/counter_web/views/layout_view_test.exs
  Elixir Projects/Counter_project/test/counter_web/views/page_view_test.exs
  Elixir Projects/Counter_project/test/support/conn_case.ex
  Elixir Projects/Counter_project/test/test_helper.exs
Labels: level1, gssoc23

#1367 OverLay Animation over an image CSS
  Animations-CSS/OverlayAnimation-Humaira/images/bot.jpg
  Animations-CSS/OverlayAnimation-Humaira/index.html
  Animations-CSS/OverlayAnimation-Humaira/styles.css
Labels: level1, gssoc23

#1960 Added Contact Us page and improved footer
  Frontend-Projects/AdventureAwaits/contactus.html
  Frontend-Projects/AdventureAwaits/css/contactus.css
  Frontend-Projects/AdventureAwaits/index.html
Labels: level1, gssoc23

#1959 Add cred home page
  Frontend-Projects/CRED Home Page/images/logo.png
  Frontend-Projects/CRED Home Page/index.html
  Frontend-Projects/CRED Home Page/style.css
Labels: level1, gssoc23

#1962 Add a creative Footer Scetion #1664
  Repository_web_page/index.html
  Repository_web_page/style.css
Labels: level1, gssoc23

#1985 Weather
  Frontend-Projects/dad-jokes-generator/index.html
  Frontend-Projects/dad-jokes-generator/index.js
  Frontend-Projects/weather-app/index.html
  Frontend-Projects/weather-app/index.js
  Frontend-Projects/weather-app/style.css
Labels: level2, gssoc23

#1306 to-do-list updated
  Frontend-Projects/To Do LIst/index.html
  Frontend-Projects/To Do LIst/styles.css
  Frontend-Projects/To Do LIst/to-do-list.png
  Frontend-Projects/To Do LIst/top.png
Labels: level1, gssoc23

#2080 [ADD]: INTRO COMPONENT WITH SIGNUP FORM 💡
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/README.md
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/design/active-states.jpg
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/design/desktop-design.jpg
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/design/desktop-preview.jpg
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/design/mobile-design.jpg
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/fonts/Poppins-Bold.woff
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/fonts/Poppins-Medium.woff
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/fonts/Poppins-Regular.woff
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/fonts/Poppins-SemiBold.woff
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/images/bg-intro-desktop.png
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/images/bg-intro-mobile.png
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/images/checkmark.svg
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/images/favicon-16x16.png
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/images/favicon-32x32.png
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/images/icon-error.svg
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/images/score.webp
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/images/site.webmanifest
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/index.html
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/main.js
  Frontend-Projects/Intro_Component_With_Sign_Up_Form/styles.css
Labels: level2, gssoc23

#2474 Added Advice Generator
  Frontend-Projects/Advice_Generator/index.html
  Frontend-Projects/Advice_Generator/index.js
  Frontend-Projects/Advice_Generator/style.css
Labels: level2, gssoc23

#2303 Updated google UI
  Frontend-Projects/google-clone/google.js
  Frontend-Projects/google-clone/images.css
  Frontend-Projects/google-clone/images.html
  Frontend-Projects/google-clone/images/account.png
  Frontend-Projects/google-clone/images/arts and culture.png
  Frontend-Projects/google-clone/images/blogger.png
  Frontend-Projects/google-clone/images/books.png
  Frontend-Projects/google-clone/images/calender.png
  Frontend-Projects/google-clone/images/chat.png
  Frontend-Projects/google-clone/images/chrome web.png
  Frontend-Projects/google-clone/images/classroom.png
  Frontend-Projects/google-clone/images/contacts.png
  Frontend-Projects/google-clone/images/docs.png
  Frontend-Projects/google-clone/images/drive.png
  Frontend-Projects/google-clone/images/earth.png
  Frontend-Projects/google-clone/images/finance.png
  Frontend-Projects/google-clone/images/forms.png
  Frontend-Projects/google-clone/images/gimages.png
  Frontend-Projects/google-clone/images/gmail.png
  Frontend-Projects/google-clone/images/google ads.png
  Frontend-Projects/google-clone/images/google one.png
  Frontend-Projects/google-clone/images/google store.png
  Frontend-Projects/google-clone/images/hangouts.png
  Frontend-Projects/google-clone/images/jamboard.png
  Frontend-Projects/google-clone/images/keep.png
  Frontend-Projects/google-clone/images/lens.webp
  Frontend-Projects/google-clone/images/maps.png
  Frontend-Projects/google-clone/images/meet.png
  Frontend-Projects/google-clone/images/mic.png
  Frontend-Projects/google-clone/images/my ad center.png
  Frontend-Projects/google-clone/images/news.png
  Frontend-Projects/google-clone/images/photos.png
  Frontend-Projects/google-clone/images/play.png
  Frontend-Projects/google-clone/images/saved.png
  Frontend-Projects/google-clone/images/search.png
  Frontend-Projects/google-clone/images/sheets.png
  Frontend-Projects/google-clone/images/shopping.png
  Frontend-Projects/google-clone/images/slides.png
  Frontend-Projects/google-clone/images/translate.png
  Frontend-Projects/google-clone/images/travel.png
  Frontend-Projects/google-clone/images/youtube.png
  Frontend-Projects/google-clone/index.css
  Frontend-Projects/google-clone/index.html
Labels: level2, gssoc23

#2305 updated claymorphism-profile-card
  Frontend-Projects/claymorphism-profile-card/index.html
  Frontend-Projects/claymorphism-profile-card/style.css
Labels: level2, gssoc23

#2306 adds a new project -> image editor
  Frontend-Projects/image editor/css/style.css
  Frontend-Projects/image editor/favicon.jpg
  Frontend-Projects/image editor/index.html
  Frontend-Projects/image editor/js/script.js
Labels: level2, gssoc23

#2308 Dice game
  README.md
Labels: level1, gssoc23

#2309 SignIn and SignUp page added for the disney hotstar clone
  Frontend-Projects/disney hotstar clone/signin.html
  Frontend-Projects/disney hotstar clone/signup.html
  Frontend-Projects/disney hotstar clone/styles.css
Labels: level2, gssoc23

#2316 Added a Rfooter with Some Changes
  Footers/Rfooter/css/style.css
  Footers/Rfooter/index.html
Labels: level2, gssoc23

#2396 Added JS Games Catch Me if You Can & Move the Ball - Issue No. - 2001
  Js-Games/Catch Me If You Can/index.html
  Js-Games/Catch Me If You Can/script.js
  Js-Games/Catch Me If You Can/style.css
  Js-Games/Move the Ball/index.html
  Js-Games/Move the Ball/script.js
  Js-Games/Move the Ball/style.css
Labels: level3, gssoc23

#2397 Added JS Project - Percentage Scored Issue no. #2271
  Js-Projects/Percentage Scored/index.html
  Js-Projects/Percentage Scored/script.js
  Js-Projects/Percentage Scored/style.css
Labels: level2, gssoc23

#2398 Added CSS - Style Animations Issue No #2272
  Animations-CSS/CSS - Style Animations/3DCube.html
  Animations-CSS/CSS - Style Animations/Animation1.html
  Animations-CSS/CSS - Style Animations/Animation2.html
  Animations-CSS/CSS - Style Animations/Animations.html
  Animations-CSS/CSS - Style Animations/Styles.css
  Animations-CSS/CSS - Style Animations/style.css
  Animations-CSS/CSS - Style Animations/style1.css
  Animations-CSS/CSS - Style Animations/style2.css
Labels: level2, gssoc23

#2399 Added Frontend Project - PhoneHub Issue No. #2274
  Frontend-Projects/PhoneHub Project/index.html
  Frontend-Projects/PhoneHub Project/media/logo.png
  Frontend-Projects/PhoneHub Project/package-lock.json
  Frontend-Projects/PhoneHub Project/package.json
  Frontend-Projects/PhoneHub Project/tailwind.config.js
Labels: level2, gssoc23

#2400 Fixed the main page
  Frontend-Projects/Fitness centre Website/index.html
Labels: level2, gssoc23

#2402 fixes the UI of membership page
  Frontend-Projects/Fitness centre Website/membership.html
Labels: level2, gssoc23

#2403 Fixes website's blog page
  Frontend-Projects/Fitness centre Website/blog latest.html
Labels: level2, gssoc23

#2404 resolves CSS styling for BMI calculator section of the website
  Frontend-Projects/Fitness centre Website/assets/css/BMI.css
Labels: level1, gssoc23

#2405 Fixes the Any Query user interface
  Frontend-Projects/Fitness centre Website/Contactus.html
Labels: level1, gssoc23

#2473 Added Brick Breaker Game in Java Projects
  Java Projects/Brick Breaker Game/BrickBreakerGame.java
  Java Projects/Brick Breaker Game/README.md
  Java Projects/Brick Breaker Game/brick.png
Labels: level2, gssoc23

#2518 added BMI calculator using java Gui
  Java Projects/BMI calculator/BMICalculator.java
  Java Projects/BMI calculator/README.md
Labels: level2, gssoc23

#2300 Add Text Animation Project
  Animations-CSS/Text Animation/index.html
  Animations-CSS/Text Animation/styles.css
  README.md
Labels: level2, gssoc23

#2482 [GSSoC'23] Added Parkinson's Disease Detector Project
  ML Projects/Parkinson's Disease Detector/Parkinsson disease.csv
  ML Projects/Parkinson's Disease Detector/README.md
  ML Projects/Parkinson's Disease Detector/app.py
  ML Projects/Parkinson's Disease Detector/diagonise.ipynb
  ML Projects/Parkinson's Disease Detector/trained_model.sav
Labels: level3, gssoc23

#2489 Adding project
  Python Projects/News Reader/README.md
  Python Projects/News Reader/main.py
Labels: level2, gssoc23

#2112 Food Ordering Website
  Frontend-Projects/Food ordering website/index.html
Labels: level1, gssoc23

#2733 Revamped the Educational Courses project
  Frontend-Projects/Educational Course website/about.html
  Frontend-Projects/Educational Course website/contact.html
  Frontend-Projects/Educational Course website/courses.html
  Frontend-Projects/Educational Course website/css/style.css
  Frontend-Projects/Educational Course website/index.html
Labels: level2, gssoc23

#2752 Documentation for Github user search
  Frontend-Projects/github-user-search/README.md
  Frontend-Projects/github-user-search/images/github search.png
Labels: level1, gssoc23

#2578 Added Sorting Visualizer Project
  React-JS Projects/Sorting-Visualizer/.gitignore
  React-JS Projects/Sorting-Visualizer/Images/Result 1.png
  React-JS Projects/Sorting-Visualizer/Images/Result 2.png
  React-JS Projects/Sorting-Visualizer/Images/Result 3.png
  React-JS Projects/Sorting-Visualizer/README.md
  React-JS Projects/Sorting-Visualizer/package-lock.json
  React-JS Projects/Sorting-Visualizer/package.json
  React-JS Projects/Sorting-Visualizer/public/favicon.ico
  React-JS Projects/Sorting-Visualizer/public/index.html
  React-JS Projects/Sorting-Visualizer/public/logo192.png
  React-JS Projects/Sorting-Visualizer/public/logo512.png
  React-JS Projects/Sorting-Visualizer/public/manifest.json
  React-JS Projects/Sorting-Visualizer/public/robots.txt
  React-JS Projects/Sorting-Visualizer/src/App.css
  React-JS Projects/Sorting-Visualizer/src/App.js
  React-JS Projects/Sorting-Visualizer/src/App.test.js
  React-JS Projects/Sorting-Visualizer/src/SortingVisualizer/SortingVisualizer.css
  React-JS Projects/Sorting-Visualizer/src/SortingVisualizer/SortingVisualizer.js
  React-JS Projects/Sorting-Visualizer/src/index.css
  React-JS Projects/Sorting-Visualizer/src/index.js
  React-JS Projects/Sorting-Visualizer/src/logo.svg
  React-JS Projects/Sorting-Visualizer/src/reportWebVitals.js
  React-JS Projects/Sorting-Visualizer/src/serviceWorker.js
  React-JS Projects/Sorting-Visualizer/src/setupTests.js
  React-JS Projects/Sorting-Visualizer/src/sortingAlgorithms/bubbleSort.js
  React-JS Projects/Sorting-Visualizer/src/sortingAlgorithms/insertionSort.js
  React-JS Projects/Sorting-Visualizer/src/sortingAlgorithms/mergeSort.js
Labels: level2, gssoc23

#2602 Hover effect Added
  Frontend-Projects/Spotify Clone/script.js
  Frontend-Projects/Spotify Clone/style.css
Labels: level1, gssoc23

#2624 Responsive_Navbar_React GSSOC23 added under #2411
  Navbars/Responsive_Navbar_React GSSOC23/README.md
  Navbars/Responsive_Navbar_React GSSOC23/package-lock.json
  Navbars/Responsive_Navbar_React GSSOC23/package.json
  Navbars/Responsive_Navbar_React GSSOC23/public/favicon.ico
  Navbars/Responsive_Navbar_React GSSOC23/public/index.html
  Navbars/Responsive_Navbar_React GSSOC23/public/logo192.png
  Navbars/Responsive_Navbar_React GSSOC23/public/logo512.png
  Navbars/Responsive_Navbar_React GSSOC23/public/manifest.json
  Navbars/Responsive_Navbar_React GSSOC23/public/robots.txt
  Navbars/Responsive_Navbar_React GSSOC23/src/App.css
  Navbars/Responsive_Navbar_React GSSOC23/src/App.js
  Navbars/Responsive_Navbar_React GSSOC23/src/App.test.js
  Navbars/Responsive_Navbar_React GSSOC23/src/Assests/bars-solid.svg
  Navbars/Responsive_Navbar_React GSSOC23/src/Components.js/Navbar.js
  Navbars/Responsive_Navbar_React GSSOC23/src/Components.js/NavbarStyle.css
  Navbars/Responsive_Navbar_React GSSOC23/src/index.css
  Navbars/Responsive_Navbar_React GSSOC23/src/index.js
  Navbars/Responsive_Navbar_React GSSOC23/src/logo.svg
  Navbars/Responsive_Navbar_React GSSOC23/src/reportWebVitals.js
  Navbars/Responsive_Navbar_React GSSOC23/src/setupTests.js
Labels: level2, gssoc23

#2630 Added Quiz Game
  Js-Games/Quiz_Game/README.md
  Js-Games/Quiz_Game/css/style.css
  Js-Games/Quiz_Game/css/styleQuiz.css
  Js-Games/Quiz_Game/index.html
  Js-Games/Quiz_Game/js/index.js
  Js-Games/Quiz_Game/js/indexQuiz.js
  Js-Games/Quiz_Game/quiz.html
  README.md
Labels: level2, gssoc23

#2641 Student database
  c_pojects/student.c
Labels: level2, gssoc23

#2648 User signup and login page using PHP
  PHP Projects/User_Signup_Login_with_database/PHP Files/database.php
  PHP Projects/User_Signup_Login_with_database/PHP Files/index.php
  PHP Projects/User_Signup_Login_with_database/PHP Files/login-success.php
  PHP Projects/User_Signup_Login_with_database/PHP Files/login.php
  PHP Projects/User_Signup_Login_with_database/PHP Files/logout.php
  PHP Projects/User_Signup_Login_with_database/PHP Files/signup-success.php
  PHP Projects/User_Signup_Login_with_database/PHP Files/signup.php
  PHP Projects/User_Signup_Login_with_database/README.md
  PHP Projects/User_Signup_Login_with_database/SQL Table/user_details.sql
Labels: level2, gssoc23

#2650 Added Website
  Frontend-Projects/Valient-Institute-Site-main/Images/LOGO.jpeg
  Frontend-Projects/Valient-Institute-Site-main/Images/background.png
  Frontend-Projects/Valient-Institute-Site-main/Images/fav.jpg
  Frontend-Projects/Valient-Institute-Site-main/Images/profile-1.jpeg
  Frontend-Projects/Valient-Institute-Site-main/Images/profile-2.jpeg
  Frontend-Projects/Valient-Institute-Site-main/Images/profile-3.jpeg
  Frontend-Projects/Valient-Institute-Site-main/index.html
  Frontend-Projects/Valient-Institute-Site-main/script.js
  Frontend-Projects/Valient-Institute-Site-main/style.css
Labels: level2, gssoc23

#2653 Added Scroll-to-top button
  Frontend-Projects/fruit_website/app.js
  Frontend-Projects/fruit_website/images/ToTop.jpg
  Frontend-Projects/fruit_website/index.html
  Frontend-Projects/fruit_website/styles.css
Labels: level1, gssoc23

#2655 added digital clock
  Java Projects/Main.java
  Java Projects/MyWindow.java
  Java Projects/README.md
Labels: level2, gssoc23
